### ISSUE TITLE
Error with the module DHCP SPOOF

### ISSUE THREAD

**Issue by clshack** [hatRiot/zarp#18]
Hi to all,
I like this tool and I want report this bug.
If I active the module dhcp spoof, and on my virtual machine windows i put these commands:
ipconfig /release
ipconfig /renew

On the zarp console I have this error:
```
0) Back
> Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/zarp/src/modules/poison/dhcp.py", line 50, in netsniff
    stopper=self.test_stop, stopperTimeout=3)
  File "/root/zarp/src/lib/scapy/sendrecv.py", line 594, in sniff
    r = prn(p)
  File "/root/zarp/src/modules/poison/dhcp.py", line 142, in pkt_handler
    log_msg('Sent DHCP offer for \'%s\' to \'%s\''
NameError: global name 'log_msg' is not defined
```
I want also report that if I fix the problem about the function 'log_msg' I encurred into this error:
```
Handed '192.168.40.130' out to '00:0c:29:8a:d1:cb'
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 552, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 505, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/root/zarp/src/modules/poison/dhcp.py", line 50, in netsniff
    stopper=self.test_stop, stopperTimeout=3)
  File "/root/zarp/src/lib/scapy/sendrecv.py", line 594, in sniff
    r = prn(p)
  File "/root/zarp/src/modules/poison/dhcp.py", line 106, in pkt_handler
    tmp = ARPSpoof()
NameError: global name 'ARPSpoof' is not defined
```

**Comment by hatRiot** [comment]
Thanks for the report @clshack; looks like I missed an import.  Will get this pushed into dev tonight, leaving open until then.

**Comment by hatRiot** [comment]
Both issues have been fixed, thanks for the report!  Fix is currently in dev, and will make it into master on next release.
