### ISSUE TITLE
Install on Mac OS X?

### ISSUE THREAD

**Issue by nntoan** [hatRiot/zarp#19]
Hi,

It currently unable to install on OS X, as your said Scapy is package inside Zarp but I got this error while import config

```ImportError: No module named pcapy```

**Comment by hatRiot** [comment]
Pcapy is a separate requirement of scapy.  Have you tried installing the pcapy package via pip?

**Comment by nntoan** [comment]
Hello,
I installed pcapy via pip without any error. But when I tried to install Zarp once again, I got this:

```
{ zarp } master » sudo python zarp.py                                                                                 ~/GitProjects/zarp 1
Traceback (most recent call last):
  File "zarp.py", line 14, in <module>
    import config
  File "/Users/macbook/GitProjects/zarp/src/core/config.py", line 1, in <module>
    import util
  File "/Users/macbook/GitProjects/zarp/src/core/util.py", line 10, in <module>
    import scapy.arch
  File "/Users/macbook/GitProjects/zarp/src/lib/scapy/arch/__init__.py", line 71, in <module>
    from bsd import *
  File "/Users/macbook/GitProjects/zarp/src/lib/scapy/arch/bsd.py", line 10, in <module>
    from unix import *
  File "/Users/macbook/GitProjects/zarp/src/lib/scapy/arch/unix.py", line 17, in <module>
    from pcapdnet import *
  File "/Users/macbook/GitProjects/zarp/src/lib/scapy/arch/pcapdnet.py", line 157, in <module>
    import dnet
ImportError: No module named dnet
```

**Comment by bwall** [comment]
Did you try to install dnet via pip?

**Comment by nntoan** [comment]
There is no luck for me, it tell me there is no dnet library, I really don't know why...
