### ISSUE TITLE
Can't install Zarp OS X 10.10

### ISSUE THREAD

**Issue by nntoan** [hatRiot/zarp#25]
I'm using Homebrew Python 2.7

After execute this command
```bash
pip install -r requirements.txt
```

I got this

```
OpenSSL/crypto/crl.c:6:23: error: static declaration of 'X509_REVOKED_dup' follows non-static declaration
    static X509_REVOKED * X509_REVOKED_dup(X509_REVOKED *orig) {
                          ^
    /usr/local/opt/openssl/include/openssl/x509.h:751:15: note: previous declaration is here
    X509_REVOKED *X509_REVOKED_dup(X509_REVOKED *rev);
                  ^
    1 error generated.
    error: command 'clang' failed with exit status 1

    ----------------------------------------
Command "/usr/local/opt/python/bin/python2.7 -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-mk9jH8/pyOpenSSL/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-WMIzPp-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-mk9jH8/pyOpenSSL
```

**Comment by nntoan** [comment]
I found the solution for this:
Change the last line in **requirements.txt** to this `pyOpenSSL==0.14`

**Comment by hatRiot** [comment]
Thanks @nntoan, I'll look into this.  It's possible that @awhitehatter specified the wrong pyOpenSSL version in the requirements file.

**Comment by the-c0d3r** [comment]
I got this on Mac OS 10.11.5, after getting the same error, and changing openssl version to 0.14. 

```
Traceback (most recent call last):
  File "zarp.py", line 14, in <module>
    import config
  File "/Users/X/programming/tools/zarp/src/core/config.py", line 4, in <module>
    from scapy.all import *
  File "/Users/X/programming/tools/zarp/src/lib/scapy/all.py", line 22, in <module>
    from route import *
  File "/Users/X/programming/tools/zarp/src/lib/scapy/route.py", line 158, in <module>
    conf.route=Route()
  File "/Users/X/programming/tools/zarp/src/lib/scapy/route.py", line 18, in __init__
    self.resync()
  File "/Users/X/programming/tools/zarp/src/lib/scapy/route.py", line 27, in resync
    self.routes = read_routes()
  File "/Users/X/programming/tools/zarp/src/lib/scapy/arch/unix.py", line 83, in read_routes
    ifaddr = scapy.arch.get_if_addr(netif)
  File "/Users/X/programming/tools/zarp/src/lib/scapy/arch/__init__.py", line 32, in get_if_addr
    return socket.inet_ntoa(get_if_raw_addr(iff))
  File "/Users/X/programming/tools/zarp/src/lib/scapy/arch/pcapdnet.py", line 185, in get_if_raw_addr
    return i.get(ifname)["addr"].data
  File "dnet.pyx", line 990, in dnet.intf.get
OSError: Device not configured
```
I think it is because the program can't figure out the interface name on Mac. I'll look for possible solutions, and maybe even hardcoding the interface name.

**Comment by bwall** [comment]
OSX!!!!!!

**Comment by krishpranav** [comment]
rather try:
python -m pip install -r requirements.txt
python zarp.py
