### ISSUE TITLE
zarp can not run 

### ISSUE THREAD

**Issue by x4ng** [hatRiot/zarp#4]
Traceback (most recent call last):
  File "./zarp.py", line 229, in <module>
    main()
  File "./zarp.py", line 88, in main
    loader.load()
  File "./zarp.py", line 71, in load
    'src.modules.attacks.%s' % module, 'attacks'), module)
  File "/usr/lib/python2.7/importlib/**init**.py", line 37, in import_module
    **import**(name)
  File "/home/x4ng/下载/zarp-master/src/modules/attacks/beef_hook.py", line 2, in <module>
    from libmproxy import controller, proxy, platform
  File "/home/x4ng/下载/zarp-master/src/lib/libmproxy/proxy.py", line 19, in <module>
    from netlib import odict, tcp, http, wsgi, certutils, http_status, http_auth
ImportError: No module named netlib

where netlib is?

**Comment by ttwsgf** [comment]
Hey, what do you do about it, how do you fix it?
`[-] Module src.modules.attacks.replacer failed to load! (cannot import name odict)
[-] Module src.modules.attacks.pemod failed to load! (cannot import name odict)
[-] Module src.modules.attacks.beef_hook failed to load! (cannot import name odict)`
thank
