### ISSUE TITLE
zarp.py and modules not working

### ISSUE THREAD

**Issue by BlancoBAM** [hatRiot/zarp#50]
python zarp.py
Traceback (most recent call last):
  File "/home/blanco/zarp/zarp.py", line 14, in <module>
    import config
  File "/home/blanco/zarp/src/core/config.py", line 106
    except Exception, e:
           ^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

**Comment by montha20** [comment]
python zarp.py
Traceback (most recent call last):
  File "/home/blanco/zarp/zarp.py", line 14, in <module>
    import config
  File "/home/blanco/zarp/src/core/config.py", line 106
    except Exception, e:
           ^^^^^^^^^^^^
SyntaxError: multiple exception types must be parenthesized

**Comment by montha20** [comment]
https://github.com/hatRiot/zarp/issues/50#issuecomment-4364839933

**Comment by montha20** [comment]
``6
